openapi: 3.0.3
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing tasks
servers:
  - url: http://localhost:8080
paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Returns a list of all tasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/TasksList"
  
    post:
      summary: Create new tasks
      description: Create a list of new tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/TaskCreateList"
      responses:
        "201":
          description: Tasks created successfully
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/TasksList"
    
    delete:
      summary: Delete multiple tasks
      description: Delete tasks by their IDs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskDeleteRequest"
      responses:
        "200":
          description: Tasks deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TasksList"

  /tasks/{id}:
    get:
      summary: Get task by ID
      description: Returns a specific task by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Task ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                error: "Task not found"
    
    delete:
      summary: Delete task by ID
      description: Delete a specific task by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Task ID
      responses:
        "200":
          description: Task deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the task
          example: 1
        title:
          type: string
          description: Title of the task
          example: "Faire les courses"
        completed:
          type: boolean
          description: Completion status of the task
          example: false
      required:
        - id
        - title
        - completed

    TasksList:
      type: array
      items:
        $ref: "#/components/schemas/Task"
      description: List of tasks

    TaskCreate:
      type: object
      properties:
        title:
          type: string
          description: Title of the task
          example: "Nouvelle tâche"
        completed:
          type: boolean
          description: Completion status of the task
          example: false
      required:
        - title

    TaskCreateList:
      type: array
      items:
        $ref: "#/components/schemas/TaskCreate"
      description: List of tasks to create

    TaskDeleteRequest:
      type: object
      properties:
        ids:
          type: array
          items:
            type: integer
          description: List of task IDs to delete
          example: [1, 2, 3]
      required:
        - ids

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error